### ISSUE TITLE
Numbers in IRC color code is send to Telegram

### ISSUE THREAD

**Issue by cuihaoleo** [tuna/fishroom#13]
Like this:
![screenshot_20160320_093924](https://cloud.githubusercontent.com/assets/889871/13902351/b4806312-ee7f-11e5-8533-779cc2c48534.png)

**Comment by farseerfc** [comment]
This issue is still reproducible in `#archlinux-cn`.
![2016-03-27-000433_2448x565_scrot](https://cloud.githubusercontent.com/assets/861563/14060695/6868c2dc-f3af-11e5-9af6-e42f5aa98f01.png)

**Comment by bigeagle** [comment]
This should be solved by pull request #16, which is still work in progress.

**Comment by bigeagle** [comment]
@farseerfc would you like to test this? it should be fixed by 779659ca0ef5ec788c1baf3f97ec217f2d9254dc
