### ISSUE TITLE
Missing text with picture send by Telegram

### ISSUE THREAD

**Issue by zhsj** [tuna/fishroom#14]
![image](https://cloud.githubusercontent.com/assets/227180/13903620/21ac3e64-eebe-11e5-87ad-bb456a744fad.png)

![image](https://cloud.githubusercontent.com/assets/227180/13903618/0f7bfcb6-eebe-11e5-9e07-b88dde30e0fc.png)

**Comment by bigeagle** [comment]
closed by 4f8ca82d6688c620580e133df543966f77be9fd4
