### ISSUE TITLE
long message issue

### ISSUE THREAD

**Issue by ZWindL** [tuna/fishroom#54]
When the users from telegram send long messages, the long message link to irc becomes strange.
[screeshot](http://img.vim-cn.com/b2/6f46fbcbd0585438a1b7d504884532e468aa78.png)
![screenshot_20161204_140653](https://cloud.githubusercontent.com/assets/5116996/20864510/784e1b6a-ba2f-11e6-8876-2de9ae2814f3.png)

**Comment by SilverRainZ** [comment]
![](http://img.tjm.moe/94/045346037cc815ba58e7015062971308e10e07.png)

**Comment by bigeagle** [comment]
卧槽！

**Comment by bigeagle** [comment]
fixed
