### ISSUE TITLE
TUNA 的鱼屋坏了

### ISSUE THREAD

**Issue by heroxbd** [tuna/fishroom#86]
召唤 @xiaq @bigeagle

**Comment by xiaq** [comment]
修好了🎵

是 RancherOS 自带的一个服务有 memory leak（https://github.com/rancher/os/issues/2258 ）导致了 OOM，升级一下就好了。

只是因为之前把数据库放在了 rootfs 里，而 RancherOS 升级的时候会直接替换 rootfs，之前的记录都没了……
